language: elixir

sudo: false

elixir: 1.9.0
otp_release: 22.0

stages:
  - check formatted
  - test

env:
  global:
    - MIX_ENV=test

cache:
  directories:
    - deps
    - priv/plts

jobs:
  include:
    - stage: test
      script:
        - mix test

    - stage: check formatted
      script: mix format --check-formatted
      before_install: skip
